target 'GitHubViewer' do
  use_frameworks!
  platform :ios, '16'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
  
  pod 'Firebase/Analytics'      # https://firebase.google.com/docs/analytics/get-started?platform=ios
  pod 'Firebase/DynamicLinks'   # https://firebase.google.com/docs/dynamic-links/ios/create
  pod 'Firebase/Crashlytics'    # https://firebase.google.com/docs/crashlytics/get-started?platform=ios
  
  pod 'AlertToast', '1.3.7'                         # toast
  pod 'lottie-ios', '3.5.0'                         # lottie
  pod 'SwiftGen', '6.5.1'                           # gen resources
  pod 'RealmSwift'                                  # db
  pod 'Kingfisher'                                  # images
  pod 'Alamofire', '~> 5.4.0'                       # HTTP client
  pod 'AlamofireNetworkActivityLogger', '~> 3.4.0'  # HTTP Logger
  pod 'SwiftLint'                                   # code style
  pod 'SwiftFormat/CLI'                             # code style format
  
  ## KMM
  pod 'shared', :path => '../shared'
end
