platform :ios, '13.0'

target 'GitHubViewer' do
  
  use_frameworks!
  
  pod 'AlertToast', '1.3.7'     # toast
  pod 'lottie-ios'              # lottie
  pod 'SwiftGen', '6.5.1'       # gen resources
  pod 'RealmSwift'              # db
  pod 'Kingfisher', '~> 7.0'    # images
  pod 'Alamofire', '~> 5.4'     # HTTP client
  pod 'SwiftLint'               # code style
  pod 'SwiftFormat/CLI'         # code style format
end
