export const enLocalization = {
    translation: {
        onboarding: {
            item_1_title: "About the app",
            item_1_desc: "This is a Kotlin Multiplatform demo app using the public GitHub REST API. The development of the application took place in 4 stages.",
            item_2_title: "First stage",
            item_2_desc: "Application on Jetpack Compose, MVVM and all the latest stack surrounding this technology.",
            item_3_title: "Second phase",
            item_3_desc: "Application on swiftUI, MVVM and the whole latest stack surrounding this technology.",
            item_4_title: "Third stage",
            item_4_desc: "Development of a \"shared\" Kotlin Multiplatform module for interaction with applications.",
            item_5_title: "Fourth stage",
            item_5_desc: "React app using the \"shared\" module we developed earlier. That's all.",
            btn_next: "Next",
            btn_back: "Back",
            btn_done: "Done",
        },
        welcome: {
            title: "Welcome to\nGitHub Viewer!",
            subtitle: "The app is written using the latest stack on ios and android.\nKeywords: KMM, MVVM, Jetpack Compose, SwiftUI",
            version: "Version: 0.0.1",
            btn: "Get started",
        },
        signIn: {
            title: "Sign In",
            input_nickname: "Nickname",
            input_nickname_error: "Nickname is required",
            btn: "Submit",
        },
        repos: {
            title: 'Repos',
            chart_1_title: "Star",
            chart_1_subtitle: "Positive ratings",
            chart_2_title: "Forks",
            chart_2_subtitle: "Copy of a repository",
            block_issue: 'Issue',
            block_watchers: 'Watchers',
            block_size: 'Size',
            label_license: 'License',
            label_visibility: 'Is visibility',
            label_owner: 'Owner',
            label_updated_at: 'Updated',
            label_created_at: 'Created',
            label_description: 'Description',
            edit: {
                form_name_label: 'Name',
                form_description_label: 'Description',
                form_is_private: 'Private Repo',
                form_name_is_required: 'Name is required',
                form_description_is_required: 'Description is required',
            }
        },
        profile: {
            title_profile: 'Profile',
            title_follower: 'Followers',
            block_public_repos: 'Pub Repos',
            block_followers: 'Followers',
            block_following: 'Following',
            label_company: 'Company',
            label_blog: 'Blog',
            label_location: 'Location',
            label_created_at: 'Date created profile',
            label_bio: 'Bio',
            edit: {
                form_name_label: 'Name',
                form_blog_label: 'Blog URL',
                form_twitter_label: 'Twitter nickname',
                form_company_label: 'Company',
                form_location_label: 'Location',
                form_bio_label: 'Bio',
                form_name_is_required: 'Name is required',
            }
        },
        common: {
            dialog_logout_title: 'Exit the application',
            dialog_logout_desc: 'You will be redirected to the login page. Is this what you want?',
            menu_en_ru: 'Enable ru-RU',
            menu_theme: 'Theme Dark',
            menu_edit_profile: 'Edit Profile',
            menu_edit_repo: 'Edit Repo',
            dialog_btn_confirm: 'Confirm',
            dialog_btn_dismiss: 'Dismiss',
            form_btn_save: 'Save',
        }
    },
};