export const enLocalization = {
    translation: {
        onboarding: {
            item_1_title: "About the app",
            item_1_desc: "This is a demo application using the open GitHub REST API. The application is under development. Develop will take place in 3 stages.",
            item_2_title: "First stage",
            item_2_desc: "Jetpack Compose application, MVVM and the whole latest stack surrounding this technology",
            item_3_title: "Second stage",
            item_3_desc: "Development of a shared KMM module for interacting with an ios application",
            item_4_title: "Third stage",
            item_4_desc: "Application for ios on Swift using the previously developed shared module using KMM",
            item_5_title: "Acknowledgments",
            item_5_desc: "This app uses the latest Google & JetBrains & Apple. Thank them for this opportunity! Thank you for your interest! Thanks to my wife for your patience :)",
            btn_next: "Next",
            btn_back: "Back",
            btn_done: "Done",
        },
        welcome: {
            title: "Welcome to GitHub Viewer!",
            subtitle: "The app is written using the latest stack on ios and android. Keywords: KMM, MVVM, Jetpack Compose, SwiftUI",
            version: "Version: 0.0.1",
            btn: "Get started",
        },
        signIn: {
            title: "Sign In",
            input_nickname: "Nickname",
            input_nickname_error: "Nickname is required",
            btn: "Submit",
        },
        repos: {
            title: 'Repos',
            chart_1_title: "Star",
            chart_1_subtitle: "Positive ratings",
            chart_2_title: "Forks",
            chart_2_subtitle: "Copy of a repository",
            block_issue: 'Issue',
            block_watchers: 'Watchers',
            block_size: 'Size',
            label_license: 'License',
            label_visibility: 'Is visibility',
            label_owner: 'Owner',
            label_updated_at: 'Updated',
            label_created_at: 'Created',
            label_description: 'Description',
        },
        profile: {
            title_profile: 'Profile',
            title_follower: 'Followers',
            block_public_repos: 'Pub Repos',
            block_followers: 'Followers',
            block_following: 'Following',
            label_company: 'Company',
            label_blog: 'Blog',
            label_location: 'Location',
            label_created_at: 'Date created profile',
            label_bio: 'Bio',
        },
        common: {
            dialog_logout_title: 'Exit the application',
            dialog_logout_desc: 'You will be redirected to the login page. Is this what you want?',
            dialog_btn_confirm: 'Confirm',
            dialog_btn_dismiss: 'Dismiss',
            menu_en_ru: 'Enable ru-RU',
            menu_theme: 'Theme Dark',
            menu_edit_profile: 'Edit Profile',
            menu_edit_repo: 'Edit Repo',
        }
    },
};