export const ruLocalization = {
    translation: {
        onboarding: {
            item_1_title: "О приложении",
            item_1_desc: "Это демострационное приложение с использованием отрытого GitHub REST API. Приложение находится на стадии развития. Развите будет проходит в 3 этапа.",
            item_2_title: "Первый этап",
            item_2_desc: "Приложение на Jetpack Compose, MVVM и весь последний стек окрущающий эту технологию",
            item_3_title: "Второй этап",
            item_3_desc: "Разработка shared модуля KMM для взаимодействия с ios приложением",
            item_4_title: "Третий этап",
            item_4_desc: "Приложение для ios на Swift с применением разработанного раннее модуля shared с использованием KMM",
            item_5_title: "Благодарности",
            item_5_desc: "В этом приложении испльзуется последний стек технологий Google & JetBrains & Apple. Спасибо им за эту возможность!  Спасибо Вам за интерес! Спасибо моей жене за терпение :)",
            btn_next: "Далее",
            btn_back: "Назад",
            btn_done: "Конец",
        },
        welcome: {
            title: "Добро пожаловать GitHub Viewer!",
            subtitle: "Приложение написано с использованием последнего стека на ios и android. KMM, MVVM, Jetpack Compose, SwiftUI",
            version: "Версия: 0.0.1",
            btn: "Начать",
        },
        signIn: {
            title: "Вход",
            input_nickname: "Nickname",
            input_nickname_error: "Nickname обязателен",
            btn: "Войти",
        },
        repos: {
            title: 'Репки',
            chart_1_title: "Звездочки",
            chart_1_subtitle: "Позитивные оценки",
            chart_2_title: "Форки",
            chart_2_subtitle: "Копии вашей репки",
            block_issue: 'Проблемы',
            block_watchers: 'Наблюдатели',
            block_size: 'Размер',
            label_license: 'Лицензия',
            label_visibility: 'Тип видимости',
            label_owner: 'Создатель',
            label_updated_at: 'Обновлено',
            label_created_at: 'Создано',
            label_description: 'Описание',
        },
        profile: {
            title_profile: 'Профайл',
            title_follower: 'Последователи',
            block_public_repos: 'Мои репки',
            block_followers: 'Последователи',
            block_following: 'Следую',
            label_company: 'Компания',
            label_blog: 'Сайт',
            label_location: 'Местонахождение',
            label_created_at: 'Дата создания профиля',
            label_bio: 'Биография',
        },
        common: {
            dialog_logout_title: 'Выход из приложения',
            dialog_logout_desc: 'Вы будете перенаправлены на страницу входа. Это то чего вы желаете?',
            dialog_btn_confirm: 'Подтвердить',
            dialog_btn_dismiss: 'Отмена',
            menu_en_ru: 'Включить ru-RU',
            menu_theme: 'Темная тема',
            menu_edit_profile: 'Редактировать',
            menu_edit_repo: 'Редактировать',
        }
    },
};