export const ruLocalization = {
    translation: {
        onboarding: {
            item_1_title: "О приложении",
            item_1_desc: "Это демострационное приложение Kotlin Multiplatform с использованием отрытого GitHub REST API. Развитие приложение проходило в 4 этапа.",
            item_2_title: "Первый этап",
            item_2_desc: "Приложение на Jetpack Compose, MVVM и весь последний стек окрущающий эту технологию.",
            item_3_title: "Второй этап",
            item_3_desc: "Приложение на swiftUI, MVVM и весь последний стек окрущающий эту технологию.",
            item_4_title: "Третий этап",
            item_4_desc: "Разработка \"shared\" модуля Kotlin Multiplatform для взаимодействия с приложениями.",
            item_5_title: "Четвертый этап",
            item_5_desc: "Приложение React с применением разработанного раннее модуля \"shared\".\nНа этом все.",
            btn_next: "Далее",
            btn_back: "Назад",
            btn_done: "Конец",
        },
        welcome: {
            title: "Добро пожаловать\nGitHub Viewer!",
            subtitle: "Приложение написано с использованием последнего стека на ios и android.\nKMM, MVVM, Jetpack Compose, SwiftUI",
            version: "Версия: 0.0.1",
            btn: "Начать",
        },
        signIn: {
            title: "Вход",
            input_nickname: "Nickname",
            input_nickname_error: "Nickname обязателен",
            btn: "Войти",
        },
        repos: {
            title: 'Репки',
            chart_1_title: "Звездочки",
            chart_1_subtitle: "Позитивные оценки",
            chart_2_title: "Форки",
            chart_2_subtitle: "Копии вашей репки",
            block_issue: 'Проблемы',
            block_watchers: 'Наблюдатели',
            block_size: 'Размер',
            label_license: 'Лицензия',
            label_visibility: 'Тип видимости',
            label_owner: 'Создатель',
            label_updated_at: 'Обновлено',
            label_created_at: 'Создано',
            label_description: 'Описание',
            edit: {
                form_name_label: 'Название',
                form_description_label: 'Описание',
                form_is_private: 'Приватная репка',
                form_name_is_required: 'Имя обязательное',
                form_description_is_required: 'Описание обязательное',
            }
        },
        profile: {
            title_profile: 'Профайл',
            title_follower: 'Последователи',
            block_public_repos: 'Мои репки',
            block_followers: 'Последователи',
            block_following: 'Следую',
            label_company: 'Компания',
            label_blog: 'Сайт',
            label_location: 'Местонахождение',
            label_created_at: 'Дата создания профиля',
            label_bio: 'Биография',
            edit: {
                form_name_label: 'Имя',
                form_blog_label: 'Сайт URL',
                form_twitter_label: 'Twitter никнейм',
                form_company_label: 'Компания',
                form_location_label: 'Локация',
                form_bio_label: 'О себе',
            }
        },
        common: {
            dialog_logout_title: 'Выход из приложения',
            dialog_logout_desc: 'Вы будете перенаправлены на страницу входа. Это то чего вы желаете?',
            dialog_btn_confirm: 'Подтвердить',
            dialog_btn_dismiss: 'Отмена',
            menu_en_ru: 'Включить ru-RU',
            menu_theme: 'Темная тема',
            menu_edit_profile: 'Редактировать',
            menu_edit_repo: 'Редактировать',
            form_btn_save: 'Сохранить',
        }
    },
};