# modules
[libraries.accompanist_pager]
module = "com.google.accompanist:accompanist-pager"
[libraries.accompanist_swiperefresh]
module = "com.google.accompanist:accompanist-swiperefresh"
[libraries.accompanist_systemuicontroller]
module = "com.google.accompanist:accompanist-systemuicontroller"
[libraries.accompanist_navigation_animation]
module = "com.google.accompanist:accompanist-navigation-animation"

# versions
[libraries.accompanist_pager.version]
ref = "accompanistVersion"
[libraries.accompanist_swiperefresh.version]
ref = "accompanistVersion"
[libraries.accompanist_systemuicontroller.version]
ref = "accompanistVersion"
[libraries.accompanist_navigation_animation.version]
ref = "accompanistVersion"

[bundles]
accompanist = [
    "accompanist_pager",
    "accompanist_swiperefresh",
    "accompanist_systemuicontroller",
    "accompanist_navigation_animation"
]