# modules
[libraries.coil_compose]
module = "io.coil-kt:coil-compose"
[libraries.coil_appcompat]
module = "androidx.appcompat:appcompat"

# versions
[libraries.coil_compose.version]
ref = "coilVersion"
[libraries.coil_appcompat.version]
ref = "appcompatVersion"

[bundles]
coil = [
    "coil_compose",
    "coil_appcompat"
]