# modules
[libraries.compose_ui]
module = "androidx.compose.ui:ui"
[libraries.compose_tooling]
module = "androidx.compose.ui:ui-tooling"
[libraries.compose_activity]
module = "androidx.activity:activity-compose"
[libraries.compose_icons]
module = "androidx.compose.material:material-icons-extended"
[libraries.compose_constraintlayout]
module = "androidx.constraintlayout:constraintlayout-compose"
[libraries.compose_material3]
module = "androidx.compose.material3:material3"
[libraries.compose_material]
module = "androidx.compose.material:material"
[libraries.compose_paging]
module = "androidx.paging:paging-compose"

# versions
[libraries.compose_ui.version]
ref = "composeVersion"
[libraries.compose_tooling.version]
ref = "composeVersion"
[libraries.compose_activity.version]
ref = "composeVersion"
[libraries.compose_icons.version]
ref = "composeVersion"
[libraries.compose_constraintlayout.version]
ref = "constraintLayoutVersion"
[libraries.compose_material3.version]
ref = "material3Version"
[libraries.compose_material.version]
ref = "materialVersion"
[libraries.compose_paging.version]
ref = "pagingComposeVersion"

[bundles]
compose = [
    "compose_ui",
    "compose_tooling",
    "compose_activity",
    "compose_icons",
    "compose_constraintlayout",
    "compose_material3",
    "compose_material",
    "compose_paging",
]